"use client";

import { useEffect, useRef, useState } from "react";

type Attachment = { name: string; type: string; dataUrl: string; size: number };
type Message = { id: number; username: string; role: string; body: string; attachments: Attachment[]; created_at: string };
type Presence = { username: string; role: string; online: boolean; last_seen: string };
async function json(res: Response) { const text=await res.text(); try { return text?JSON.parse(text):{}; } catch { return { error:text }; } }
function time(v:string){ const d=new Date(v); return Number.isNaN(d.getTime()) ? "" : d.toLocaleTimeString([], { hour:"2-digit", minute:"2-digit" }); }

export default function ChatClient({ username, role }: { username: string; role: string }) {
  const [messages,setMessages]=useState<Message[]>([]); const [presence,setPresence]=useState<Presence[]>([]); const [body,setBody]=useState(""); const [files,setFiles]=useState<FileList|null>(null); const [status,setStatus]=useState("secure chat ready"); const [loading,setLoading]=useState(false); const bottom=useRef<HTMLDivElement|null>(null); const lastId=useRef(0);
  async function load() { try { const res=await fetch("/api/chat/state", { cache:"no-store" }); const data=await json(res); if(!res.ok) throw new Error(data.error || "chat failed"); const next=Array.isArray(data.messages)?data.messages:[]; if (next.length && next[next.length-1].id !== lastId.current && lastId.current !== 0) setStatus(`▸ new terminal message @ ${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`); lastId.current = next.length ? next[next.length-1].id : 0; setMessages(next); setPresence(Array.isArray(data.presence)?data.presence:[]); } catch(e:any){ setStatus(e.message || "chat failed"); } }
  async function send() { if ((!body.trim() && !files?.length) || loading) return; setLoading(true); setStatus("sending..."); try { const form=new FormData(); form.set("body", body); Array.from(files || []).forEach(f=>form.append("files", f)); const res=await fetch("/api/chat/messages", { method:"POST", body: form }); const data=await json(res); if(!res.ok) throw new Error(data.error || "send failed"); setBody(""); setFiles(null); const input=document.getElementById("chat-files") as HTMLInputElement | null; if(input) input.value=""; await load(); setStatus("sent"); } catch(e:any){ setStatus(e.message || "send failed"); } finally { setLoading(false); } }
  useEffect(()=>{ load(); const id=setInterval(load, 4000); return ()=>clearInterval(id); }, []);
  useEffect(()=>{ bottom.current?.scrollIntoView({ behavior:"smooth", block:"end" }); }, [messages]);
  return <div className="stack"><section className="panel stack"><div className="spread"><div><p className="badge">PRIVATE CHAT</p><h1>Terminal chat</h1><p className="muted">Signed in as {username}:{role}. Presence updates while this page is open.</p></div><button onClick={load}>sync</button></div><div className="row">{presence.map(p=><span className="badge" key={p.username}><span className={`light ${p.online ? "online" : "offline"}`}></span>{p.username}:{p.role} {p.online ? "online" : "offline"}</span>)}</div><p className="muted small">Status: {status}</p></section><section className="stack">{messages.map(m=><article className="post stack chatline" key={m.id}><div className="spread"><div><span className="badge">{m.username}:{m.role}</span> <span className="muted small">{time(m.created_at)}</span></div>{m.username===username && <span className="badge">you</span>}</div>{m.body && <pre>{m.body}</pre>}{m.attachments?.length>0 && <div className="grid">{m.attachments.map((a,i)=><div className="panel stack" key={i}><p className="muted small">{a.name} · {(a.size/1024/1024).toFixed(2)} MB</p>{a.type.startsWith("image/") ? <img className="media" src={a.dataUrl} alt={a.name}/> : <video className="media" src={a.dataUrl} controls />}</div>)}</div>}</article>)}<div ref={bottom}/></section><section className="panel stack"><textarea value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{ if(e.key==="Enter" && !e.shiftKey){ e.preventDefault(); send(); } }} placeholder="terminal message..."/><input id="chat-files" type="file" accept="image/*,video/mp4,video/webm,video/quicktime" multiple onChange={e=>setFiles(e.target.files)}/><div className="row"><button onClick={send} disabled={loading || (!body.trim() && !files?.length)}>{loading?"sending...":"send"}</button><span className="muted small">Enter sends. Shift+Enter newline. Files are stored in Neon as small encrypted-by-HTTPS data, not E2E encrypted.</span></div></section></div>;
}
