"use client";

import { useMemo, useState } from "react";

type Item = { id: string; title: string; channelTitle: string; publishedAt: string; description: string; duration?: string; viewCount?: string; likeCount?: string };
function extract(input: string) { const raw=input.trim(); if (/^[a-zA-Z0-9_-]{11}$/.test(raw)) return raw; try { const u=new URL(raw); if (u.hostname.includes("youtu.be")) return u.pathname.split("/").filter(Boolean)[0] || ""; if (u.hostname.includes("youtube.com")) { if (u.pathname.startsWith("/shorts/") || u.pathname.startsWith("/embed/")) return u.pathname.split("/").filter(Boolean)[1] || ""; return u.searchParams.get("v") || ""; } } catch {} return ""; }
async function json(res: Response) { const text=await res.text(); try { return text?JSON.parse(text):{}; } catch { return { error:text }; } }
function date(v: string) { const d=new Date(v); return Number.isNaN(d.getTime()) ? "" : d.toLocaleDateString(); }
function num(v?: string) { const n=Number(v); return Number.isFinite(n) ? new Intl.NumberFormat(undefined, { notation: "compact", maximumFractionDigits: 1 }).format(n) : "?"; }

export default function YouTubeClient() {
  const [query,setQuery]=useState(""); const [direct,setDirect]=useState(""); const [items,setItems]=useState<Item[]>([]); const [selected,setSelected]=useState<Item|null>(null); const [token,setToken]=useState(""); const [status,setStatus]=useState("text-only, no thumbnails"); const [loading,setLoading]=useState(false); const [player,setPlayer]=useState(false);
  const vid = useMemo(() => extract(direct), [direct]);
  async function search(page="") { if (!query.trim() || loading) return; setLoading(true); setStatus(page ? "loading more..." : "searching..."); try { const res=await fetch(`/api/youtube/search?q=${encodeURIComponent(query.trim())}&pageToken=${encodeURIComponent(page)}`, { cache:"no-store" }); const data=await json(res); if (!res.ok) throw new Error(data.error || "search failed"); const newItems=Array.isArray(data.items)?data.items:[]; setItems(old => page ? [...old,...newItems] : newItems); setToken(data.nextPageToken || ""); setStatus(`${page ? items.length + newItems.length : newItems.length} results loaded`); } catch(e:any){ setStatus(e.message || "search failed"); } finally { setLoading(false); } }
  async function open(id:string) { if (!id || loading) return; setLoading(true); setPlayer(false); setStatus("loading video text..."); try { const res=await fetch(`/api/youtube/video?id=${encodeURIComponent(id)}`, { cache:"no-store" }); const data=await json(res); if (!res.ok) throw new Error(data.error || "video failed"); setSelected(data); setStatus("video details loaded"); } catch(e:any){ setStatus(e.message || "video failed"); } finally { setLoading(false); } }
  return <div className="stack"><section className="panel stack"><p className="badge">YOUTUBE TEXT</p><h1>YouTube text browser</h1><p className="muted">No thumbnails are loaded. The player only loads after pressing open player.</p><div className="row"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{ if(e.key==="Enter") search(); }} placeholder="search YouTube" /><button onClick={()=>search()} disabled={loading || !query.trim()}>search</button>{token && <button onClick={()=>search(token)} disabled={loading}>more results</button>}<button onClick={()=>{setItems([]);setSelected(null);setToken("");}}>clear</button></div><div className="row"><input value={direct} onChange={e=>setDirect(e.target.value)} onKeyDown={e=>{ if(e.key==="Enter" && vid) open(vid); }} placeholder="paste URL or video ID" /><button onClick={()=>open(vid)} disabled={!vid || loading}>open by ID</button>{vid && <span className="badge">{vid}</span>}</div><p className="muted small">Status: {loading ? "loading... " : ""}{status}</p></section>{selected && <section className="panel stack"><div className="spread"><div><span className="badge">{selected.id}</span><h2>{selected.title}</h2><p className="muted">{selected.channelTitle} · {date(selected.publishedAt)} · views {num(selected.viewCount)} · likes {num(selected.likeCount)} · {selected.duration || "?"}</p></div><button onClick={()=>setSelected(null)}>close</button></div><pre>{selected.description || "No description."}</pre><div className="row"><a className="buttonlike" href={`https://www.youtube.com/watch?v=${selected.id}`} target="_blank" rel="noreferrer">open on YouTube</a><button onClick={()=>navigator.clipboard.writeText(`https://www.youtube.com/watch?v=${selected.id}`)}>copy link</button><button onClick={()=>setPlayer(v=>!v)}>{player ? "close player" : "open player"}</button></div>{player && <iframe src={`https://www.youtube-nocookie.com/embed/${selected.id}`} title={selected.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen />}</section>}<section className="stack"><div className="panel spread"><h2>Results</h2>{token && <button onClick={()=>search(token)}>more results</button>}</div>{items.map(item=><article className="post stack" key={item.id}><div className="spread"><div><h3>{item.title}</h3><p className="muted small">{item.channelTitle} · {date(item.publishedAt)} · {item.id}</p></div><button onClick={()=>open(item.id)}>open text details</button></div><p>{item.description || "No description."}</p></article>)}</section></div>;
}
