import "server-only";
import crypto from "node:crypto";
import { neon } from "@neondatabase/serverless";
import { decryptSecret, encryptSecret } from "./accounts";
const db=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is not set");return neon(process.env.DATABASE_URL)};
export async function listTenantKeys(tenantId:string){const sql=db();const rows=await sql`SELECT provider,label,created_at::text,updated_at::text FROM viewport_tenant_api_keys WHERE tenant_id=${tenantId}::uuid ORDER BY provider`;return rows as any[]}
export async function setTenantKey(tenantId:string,provider:string,value:string,label:string){const sql=db(); const allowed=["google_places","google_geocoding","pagespeed","anthropic","twilio_sid","twilio_token","twilio_from","resend"];
 if(!allowed.includes(provider))throw new Error("Unsupported provider"); if(value.trim().length<4)throw new Error("Enter a valid key"); const encrypted=await encryptSecret(value.trim());
 await sql`INSERT INTO viewport_tenant_api_keys(tenant_id,provider,label,encrypted_value) VALUES(${tenantId}::uuid,${provider},${label.slice(0,80)},${encrypted}) ON CONFLICT(tenant_id,provider) DO UPDATE SET label=EXCLUDED.label,encrypted_value=EXCLUDED.encrypted_value,updated_at=NOW()`}
export async function removeTenantKey(tenantId:string,provider:string){const sql=db();await sql`DELETE FROM viewport_tenant_api_keys WHERE tenant_id=${tenantId}::uuid AND provider=${provider}`}
export async function getTenantKey(tenantId:string,provider:string){const sql=db();const rows=await sql`SELECT encrypted_value FROM viewport_tenant_api_keys WHERE tenant_id=${tenantId}::uuid AND provider=${provider} LIMIT 1`;if(!rows.length)return "";return decryptSecret(String((rows[0] as any).encrypted_value))}
export async function saveProspect(tenantId:string,p:any){const sql=db();const id=String(p.id||p.placeId||crypto.randomUUID()).slice(0,180);await sql`INSERT INTO viewport_customer_prospects(id,tenant_id,name,category,address,phone,website,maps_url,lat,lng,status,score,notes,raw) VALUES(${id},${tenantId}::uuid,${String(p.name||"").slice(0,200)},${String(p.category||"business").slice(0,120)},${String(p.address||"").slice(0,300)},${String(p.phone||"").slice(0,80)},${String(p.website||"").slice(0,500)},${String(p.mapsUrl||p.maps_url||"").slice(0,500)},${Number(p.lat||0)},${Number(p.lng||0)},'saved',${Number(p.score||0)},'',${JSON.stringify(p)}::jsonb) ON CONFLICT(tenant_id,id) DO UPDATE SET raw=EXCLUDED.raw,updated_at=NOW()`}
export async function listProspects(tenantId:string){const sql=db();return await sql`SELECT id,name,category,address,phone,website,maps_url,lat,lng,status,score,notes,created_at::text,updated_at::text FROM viewport_customer_prospects WHERE tenant_id=${tenantId}::uuid ORDER BY updated_at DESC LIMIT 500` as any[]}
