"use client";

import { useEffect, useMemo, useState } from "react";

export type BusinessSection = "pipeline" | "contacts" | "inbox" | "sms" | "audits" | "proposals" | "inquiries" | "money" | "setup";

type LeadStatus = "new" | "saved" | "contacted" | "followup" | "interested" | "won" | "rejected";
type Lead = {
  id: string; name: string; category: string; address: string; phone: string; email: string; contactFormUrl: string;
  website: string; mapsUrl: string; rating: number | null; userRatingCount: number | null; score: number; status: LeadStatus;
  notes: string; offerPrice: string; packageName: string; nextFollowUp: string; lastContacted: string; siteQuality: string; siteNotes: string;
};
type Contact = { id: number; leadId: string; kind: string; value: string; label: string; sourceUrl: string; confidence: number; verified: boolean; primary: boolean; createdAt: string; updatedAt: string };
type Activity = { id: number; leadId: string; kind: string; summary: string; metadata: Record<string, unknown>; createdAt: string };
type Task = { id: number; leadId: string; title: string; dueAt: string; priority: string; done: boolean; createdAt: string; updatedAt: string };
type Proposal = { id: number; leadId: string; title: string; status: string; currency: string; setupAmount: number; monthlyAmount: number; depositAmount: number; validUntil: string; deliveryDays: number; revisions: number; lineItems: Array<{ label: string; amount: number; recurring?: boolean }>; notes: string; createdAt: string; updatedAt: string };
type Transaction = { id: number; leadId: string; kind: string; status: string; amount: number; currency: string; dueAt: string; paidAt: string; description: string; createdAt: string };
type Message = { id: number; leadId: string; channel: string; direction: string; sender: string; recipient: string; subject: string; body: string; externalId: string; threadId: string; status: string; unread: boolean; metadata: Record<string, unknown>; createdAt: string; updatedAt: string };
type Inquiry = { id: number; leadId: string; name: string; email: string; phone: string; message: string; sourceSite: string; status: string; createdAt: string; updatedAt: string };
type Audit = { id: number; leadId: string; url: string; strategy: string; score: number; performance: number | null; accessibility: number | null; seo: number | null; bestPractices: number | null; issues: Array<{ severity: string; label: string; detail?: string }>; facts: Record<string, unknown>; screenshot: string; createdAt: string };
type SearchRun = { id: number; query: string; location: string; bounds: Record<string, unknown>; status: string; foundCount: number; scannedCount: number; apiRequests: number; cursor: Record<string, unknown>; createdAt: string; updatedAt: string };
type Workspace = { contacts: Contact[]; activities: Activity[]; tasks: Task[]; proposals: Proposal[]; transactions: Transaction[]; messages: Message[]; inquiries: Inquiry[]; audits: Audit[]; searchRuns: SearchRun[] };
type GmailAttachment = { filename: string; mimeType: string; attachmentId: string; size: number };
type GmailMessage = { id: string; threadId: string; from: string; to: string; cc: string; subject: string; date: string; messageIdHeader: string; references: string; inReplyTo: string; snippet: string; body: string; unread: boolean; labels: string[]; attachments: GmailAttachment[] };
type GmailThread = { id: string; messages: GmailMessage[]; latest?: GmailMessage; messageCount: number; unread: boolean };

const emptyWorkspace: Workspace = { contacts: [], activities: [], tasks: [], proposals: [], transactions: [], messages: [], inquiries: [], audits: [], searchRuns: [] };
const pipeline: Array<{ key: LeadStatus; label: string }> = [
  { key: "new", label: "new" }, { key: "saved", label: "qualified" }, { key: "contacted", label: "contacted" },
  { key: "followup", label: "follow-up" }, { key: "interested", label: "interested" }, { key: "won", label: "won" }, { key: "rejected", label: "lost" },
];

function readJson(response: Response) {
  return response.text().then((text) => { try { return text ? JSON.parse(text) as any : {}; } catch { return { error: text }; } });
}
function errorText(error: unknown) { return error instanceof Error ? error.message : String(error || "operation failed"); }
function money(value: number, currency = "EUR") { return new Intl.NumberFormat("fi-FI", { style: "currency", currency }).format(Number.isFinite(value) ? value : 0); }
function dateLabel(value: string) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("fi-FI"); }
function emails(value: string) { return Array.from(value.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)).map((match) => match[0].toLowerCase()); }
function cleanPhone(value: string) { return value.replace(/[^+\d]/g, ""); }
function amountFrom(value: string) { const parsed = Number(value.replace(/[^0-9,.-]/g, "").replace(",", ".")); return Number.isFinite(parsed) ? parsed : 0; }
function download(name: string, content: string, type = "text/plain;charset=utf-8") {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url);
}
function csvCell(value: unknown) { return `"${String(value ?? "").replace(/"/g, '""')}"`; }

export default function BusinessOperationsClient({ section, username }: { section: BusinessSection; username: string }) {
  const [leads, setLeads] = useState<Lead[]>([]);
  const [workspace, setWorkspace] = useState<Workspace>(emptyWorkspace);
  const [selectedLeadId, setSelectedLeadId] = useState("");
  const [status, setStatus] = useState("business operations ready");
  const [loading, setLoading] = useState(false);
  const [filter, setFilter] = useState("");
  const selectedLead = leads.find((lead) => lead.id === selectedLeadId) || null;
  const leadMap = useMemo(() => new Map(leads.map((lead) => [lead.id, lead])), [leads]);

  async function loadAll() {
    setLoading(true);
    try {
      const [leadResponse, opsResponse] = await Promise.all([fetch("/api/business/leads", { cache: "no-store" }), fetch("/api/business/ops", { cache: "no-store" })]);
      const leadData = await readJson(leadResponse); const opsData = await readJson(opsResponse);
      if (!leadResponse.ok) throw new Error(String(leadData.error || "lead load failed"));
      if (!opsResponse.ok) throw new Error(String(opsData.error || "operations load failed"));
      const nextLeads = Array.isArray(leadData.leads) ? leadData.leads as Lead[] : [];
      setLeads(nextLeads);
      setWorkspace({
        contacts: Array.isArray(opsData.contacts) ? opsData.contacts : [], activities: Array.isArray(opsData.activities) ? opsData.activities : [],
        tasks: Array.isArray(opsData.tasks) ? opsData.tasks : [], proposals: Array.isArray(opsData.proposals) ? opsData.proposals : [],
        transactions: Array.isArray(opsData.transactions) ? opsData.transactions : [], messages: Array.isArray(opsData.messages) ? opsData.messages : [],
        inquiries: Array.isArray(opsData.inquiries) ? opsData.inquiries : [], audits: Array.isArray(opsData.audits) ? opsData.audits : [],
        searchRuns: Array.isArray(opsData.searchRuns) ? opsData.searchRuns : [],
      });
      if (!selectedLeadId && nextLeads[0]) setSelectedLeadId(nextLeads[0].id);
      setStatus(`${nextLeads.length} companies · ${Array.isArray(opsData.messages) ? opsData.messages.length : 0} communications loaded`);
    } catch (error) { setStatus(errorText(error)); } finally { setLoading(false); }
  }

  async function action(actionName: string, body: Record<string, unknown>) {
    const response = await fetch("/api/business/ops", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: actionName, ...body }) });
    const data = await readJson(response);
    if (!response.ok) throw new Error(String(data.error || `${actionName} failed`));
    return data.result;
  }

  async function deleteEntity(entity: string, id: number) {
    const response = await fetch(`/api/business/ops?entity=${encodeURIComponent(entity)}&id=${id}`, { method: "DELETE" });
    const data = await readJson(response); if (!response.ok) throw new Error(String(data.error || "delete failed"));
    await loadAll();
  }

  async function updateLead(leadId: string, patch: Partial<Lead>) {
    const response = await fetch("/api/business/leads", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: leadId, ...patch }) });
    const data = await readJson(response); if (!response.ok) throw new Error(String(data.error || "lead update failed"));
    setLeads((old) => old.map((lead) => lead.id === leadId ? { ...lead, ...data.lead } : lead));
  }

  useEffect(() => { void loadAll(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, []);

  const shared = { leads, workspace, selectedLeadId, setSelectedLeadId, selectedLead, leadMap, status, setStatus, loading, setLoading, filter, setFilter, loadAll, action, deleteEntity, updateLead, username };
  return (
    <div className="stack business-ops">
      <section className="panel compact-panel">
        <div className="spread">
          <div><span className="badge">LIVE OPERATIONS</span><span className="muted small"> {status}</span></div>
          <div className="row"><input className="ops-filter" value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="filter companies/messages" /><button onClick={() => void loadAll()} disabled={loading}>sync all</button></div>
        </div>
      </section>
      {section === "pipeline" && <PipelineView {...shared} />}
      {section === "contacts" && <ContactsView {...shared} />}
      {section === "inbox" && <InboxView {...shared} />}
      {section === "sms" && <SmsView {...shared} />}
      {section === "audits" && <AuditsView {...shared} />}
      {section === "proposals" && <ProposalsView {...shared} />}
      {section === "inquiries" && <InquiriesView {...shared} />}
      {section === "money" && <MoneyView {...shared} />}
      {section === "setup" && <SetupView {...shared} />}
    </div>
  );
}

type Shared = ReturnType<typeof sharedShape>;
function sharedShape() { return {} as {
  leads: Lead[]; workspace: Workspace; selectedLeadId: string; setSelectedLeadId: (id: string) => void; selectedLead: Lead | null; leadMap: Map<string, Lead>;
  status: string; setStatus: (value: string) => void; loading: boolean; setLoading: (value: boolean) => void; filter: string; setFilter: (value: string) => void;
  loadAll: () => Promise<void>; action: (actionName: string, body: Record<string, unknown>) => Promise<any>; deleteEntity: (entity: string, id: number) => Promise<void>;
  updateLead: (leadId: string, patch: Partial<Lead>) => Promise<void>; username: string;
}; }

function LeadPicker({ leads, value, onChange, includeEmpty = true }: { leads: Lead[]; value: string; onChange: (value: string) => void; includeEmpty?: boolean }) {
  return <select value={value} onChange={(event) => onChange(event.target.value)}>{includeEmpty && <option value="">unassigned / select company</option>}{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.name} · {lead.status}</option>)}</select>;
}

function PipelineView(props: Shared) {
  const { leads, workspace, selectedLeadId, setSelectedLeadId, selectedLead, leadMap, filter, setStatus, action, updateLead, loadAll } = props;
  const [note, setNote] = useState(""); const [taskTitle, setTaskTitle] = useState(""); const [taskDue, setTaskDue] = useState("");
  const visible = leads.filter((lead) => !filter || `${lead.name} ${lead.category} ${lead.address} ${lead.email} ${lead.phone}`.toLowerCase().includes(filter.toLowerCase()));
  async function move(id: string, status: LeadStatus) { try { await updateLead(id, { status }); await action("activity.add", { leadId: id, kind: "status", summary: `Pipeline moved to ${status}` }); setStatus(`moved to ${status}`); } catch (error) { setStatus(errorText(error)); } }
  async function addNote() { if (!selectedLeadId || !note.trim()) return; try { await action("activity.add", { leadId: selectedLeadId, kind: "note", summary: note.trim() }); setNote(""); await loadAll(); } catch (error) { setStatus(errorText(error)); } }
  async function addTask() { if (!taskTitle.trim()) return; try { await action("task.save", { leadId: selectedLeadId, title: taskTitle, dueAt: taskDue || null, priority: "normal" }); setTaskTitle(""); setTaskDue(""); await loadAll(); } catch (error) { setStatus(errorText(error)); } }
  const leadActivities = workspace.activities.filter((item) => item.leadId === selectedLeadId).slice(0, 30);
  const leadTasks = workspace.tasks.filter((item) => item.leadId === selectedLeadId);
  const csv = ["name,status,category,address,email,phone,website,score,next_follow_up", ...visible.map((lead) => [lead.name, lead.status, lead.category, lead.address, lead.email, lead.phone, lead.website, lead.score, lead.nextFollowUp].map(csvCell).join(","))].join("\n");
  return <>
    <section className="panel stack">
      <div className="spread"><div><h2>Sales pipeline</h2><p className="muted small">Drag cards between columns or use the move buttons. Every change is stored in the timeline.</p></div><button onClick={() => download("business-leads.csv", csv, "text/csv;charset=utf-8")}>export CSV</button></div>
      <div className="kanban-board">
        {pipeline.map((column) => <div className="kanban-column" key={column.key} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const id = event.dataTransfer.getData("text/lead-id"); if (id) void move(id, column.key); }}>
          <div className="spread"><strong>{column.label}</strong><span className="badge">{visible.filter((lead) => lead.status === column.key).length}</span></div>
          <div className="stack compact-stack">{visible.filter((lead) => lead.status === column.key).map((lead) => <button draggable key={lead.id} className={`kanban-card ${selectedLeadId === lead.id ? "active" : ""}`} onDragStart={(event) => event.dataTransfer.setData("text/lead-id", lead.id)} onClick={() => setSelectedLeadId(lead.id)}>
            <strong>{lead.name}</strong><span className="muted small">{lead.category} · score {lead.score}</span><span className="muted small">{lead.email || lead.phone || lead.contactFormUrl || "no contact"}</span>
          </button>)}</div>
        </div>)}
      </div>
    </section>
    <div className="ops-two-column">
      <section className="panel stack"><h2>Company record</h2>{!selectedLead ? <p className="muted">Select a company.</p> : <>
        <div className="spread"><div><span className="badge">{selectedLead.status}</span><h2>{selectedLead.name}</h2><p className="muted">{selectedLead.category} · {selectedLead.address}</p></div><div className="row"><a className="buttonlike" href={selectedLead.website || selectedLead.mapsUrl || "#"} target="_blank" rel="noreferrer">open</a><select value={selectedLead.status} onChange={(event) => void move(selectedLead.id, event.target.value as LeadStatus)}>{pipeline.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></div></div>
        <div className="metric-grid"><Metric label="email" value={selectedLead.email || "none"} /><Metric label="phone" value={selectedLead.phone || "none"} /><Metric label="site" value={selectedLead.siteQuality || "unknown"} /><Metric label="offer" value={`${selectedLead.packageName || ""} ${selectedLead.offerPrice || ""}`} /></div>
        <label className="stack small">Add timeline note<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Called owner; asked to follow up Friday..." /></label><button onClick={() => void addNote()} disabled={!note.trim()}>save note</button>
        <div className="grid tight-grid"><label className="stack small">Task<input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} placeholder="Send revised mockup" /></label><label className="stack small">Due<input type="datetime-local" value={taskDue} onChange={(event) => setTaskDue(event.target.value)} /></label></div><button onClick={() => void addTask()} disabled={!taskTitle.trim()}>add follow-up task</button>
      </>}</section>
      <section className="panel stack"><h2>Tasks + timeline</h2>{leadTasks.map((task) => <div className="timeline-row" key={task.id}><label className="checkline"><input type="checkbox" checked={task.done} onChange={() => void action("task.save", { ...task, done: !task.done }).then(loadAll)} /><span><strong>{task.title}</strong><br/><span className="muted small">{dateLabel(task.dueAt)} · {task.priority}</span></span></label></div>)}{!leadTasks.length && <p className="muted">No tasks for this company.</p>}<hr/>{leadActivities.map((item) => <div className="timeline-row" key={item.id}><span className="badge">{item.kind}</span><div><p>{item.summary}</p><span className="muted small">{dateLabel(item.createdAt)} · {leadMap.get(item.leadId)?.name || "unassigned"}</span></div></div>)}</section>
    </div>
  </>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="metric"><span className="dim small">{label}</span><strong>{value}</strong></div>; }

function ContactsView(props: Shared) {
  const { leads, workspace, selectedLeadId, setSelectedLeadId, leadMap, filter, setStatus, action, deleteEntity, loadAll } = props;
  const [kind, setKind] = useState("email"); const [value, setValue] = useState(""); const [label, setLabel] = useState(""); const [confidence, setConfidence] = useState("80");
  const contacts = workspace.contacts.filter((item) => (!selectedLeadId || item.leadId === selectedLeadId) && (!filter || `${leadMap.get(item.leadId)?.name} ${item.kind} ${item.value} ${item.label}`.toLowerCase().includes(filter.toLowerCase())));
  async function save() { if (!selectedLeadId || !value.trim()) return; try { await action("contact.upsert", { leadId: selectedLeadId, kind, value, label, confidence: Number(confidence), verified: false, primary: false }); setValue(""); setLabel(""); await loadAll(); } catch (error) { setStatus(errorText(error)); } }
  return <div className="ops-two-column"><section className="panel stack"><h2>Contact directory</h2><p className="muted small">Unlike the old single lead row, this keeps every discovered email, phone, form, booking page, and social profile with its source and confidence.</p><label className="stack small">Company<LeadPicker leads={leads} value={selectedLeadId} onChange={setSelectedLeadId} /></label><div className="grid tight-grid"><label className="stack small">Type<select value={kind} onChange={(event) => setKind(event.target.value)}>{["email","phone","form","booking","whatsapp","facebook","instagram","linkedin","tiktok","other"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="stack small">Confidence<input type="number" min="0" max="100" value={confidence} onChange={(event) => setConfidence(event.target.value)} /></label></div><label className="stack small">Value<input value={value} onChange={(event) => setValue(event.target.value)} placeholder="info@company.fi or https://..." /></label><label className="stack small">Label<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="owner, reception, quote form..." /></label><button onClick={() => void save()} disabled={!selectedLeadId || !value.trim()}>save contact</button></section>
    <section className="panel stack"><div className="spread"><h2>Saved contacts</h2><span className="badge">{contacts.length}</span></div><div className="contact-table">{contacts.map((item) => <div className="contact-row" key={item.id}><div><strong>{leadMap.get(item.leadId)?.name || item.leadId}</strong><p>{item.value}</p><span className="muted small">{item.kind} · confidence {item.confidence}% · {item.label || "no label"}</span>{item.sourceUrl && <p className="muted small">source: <a href={item.sourceUrl} target="_blank" rel="noreferrer">{item.sourceUrl}</a></p>}</div><div className="row"><span className={item.verified ? "badge" : "badge warn"}>{item.verified ? "verified" : "unverified"}</span><button onClick={() => void action("contact.upsert", { ...item, verified: !item.verified }).then(loadAll)}>toggle verify</button><button className="danger" onClick={() => void deleteEntity("contact", item.id)}>×</button></div></div>)}</div></section></div>;
}

function InboxView(props: Shared) {
  const { leads, workspace, selectedLeadId, setSelectedLeadId, leadMap, filter, setStatus, action, loadAll } = props;
  const [gmail, setGmail] = useState({ connected: false, email: "", configured: false });
  const [threads, setThreads] = useState<GmailThread[]>([]); const [selectedThread, setSelectedThread] = useState<{ id: string; messages: GmailMessage[] } | null>(null);
  const [query, setQuery] = useState("in:inbox"); const [mailLoading, setMailLoading] = useState(false);
  const [to, setTo] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState("");
  async function statusCheck() { const response = await fetch("/api/email/google/status", { cache: "no-store" }); const data = await readJson(response); if (response.ok) setGmail({ connected: Boolean(data.connected), email: String(data.email || ""), configured: Boolean(data.configured) }); else setStatus(String(data.error || "Gmail status failed")); }
  async function loadThreads() { setMailLoading(true); try { const response = await fetch(`/api/email/google/threads?q=${encodeURIComponent(query)}&max=25`, { cache: "no-store" }); const data = await readJson(response); if (!response.ok) throw new Error(String(data.error || "Gmail load failed")); setThreads(Array.isArray(data.threads) ? data.threads : []); setStatus(`${data.threads?.length || 0} Gmail threads loaded`); } catch (error) { setStatus(errorText(error)); } finally { setMailLoading(false); } }
  function matchLead(message?: GmailMessage) { if (!message) return ""; const candidates = new Set([...emails(message.from), ...emails(message.to)]); const direct = leads.find((lead) => lead.email && candidates.has(lead.email.toLowerCase())); if (direct) return direct.id; const contact = workspace.contacts.find((item) => item.kind === "email" && candidates.has(item.value.toLowerCase())); return contact?.leadId || ""; }
  async function openThread(thread: GmailThread) { setMailLoading(true); try { const response = await fetch(`/api/email/google/thread?id=${encodeURIComponent(thread.id)}`, { cache: "no-store" }); const data = await readJson(response); if (!response.ok) throw new Error(String(data.error || "thread load failed")); const next = data.thread as { id: string; messages: GmailMessage[] }; setSelectedThread(next); const latest = next.messages[next.messages.length - 1]; const leadId = matchLead(latest); if (leadId) setSelectedLeadId(leadId); const replyAddress = emails(latest.from).find((email) => email !== gmail.email.toLowerCase()) || emails(latest.to).find((email) => email !== gmail.email.toLowerCase()) || ""; setTo(replyAddress); setSubject(/^re:/i.test(latest.subject) ? latest.subject : `Re: ${latest.subject}`); setBody(""); await action("message.add", { leadId, channel: "email", direction: latest.from.toLowerCase().includes(gmail.email.toLowerCase()) ? "outbound" : "inbound", sender: latest.from, recipient: latest.to, subject: latest.subject, body: latest.body, externalId: latest.id, threadId: next.id, status: "received", unread: false, metadata: { date: latest.date } }).catch(() => undefined); } catch (error) { setStatus(errorText(error)); } finally { setMailLoading(false); } }
  async function send() { if (!to || !subject || !body) return; setMailLoading(true); try { const latest = selectedThread?.messages[selectedThread.messages.length - 1]; const response = await fetch("/api/email/google/send", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId: selectedLeadId, to, subject, body, threadId: selectedThread?.id || "", inReplyTo: latest?.messageIdHeader || "", references: [latest?.references, latest?.messageIdHeader].filter(Boolean).join(" ") }) }); const data = await readJson(response); if (!response.ok) throw new Error(String(data.error || "send failed")); setBody(""); setStatus("email sent through Gmail"); await Promise.all([loadThreads(), loadAll()]); } catch (error) { setStatus(errorText(error)); } finally { setMailLoading(false); } }
  async function gmailAction(actionName: string) { if (!selectedThread) return; const response = await fetch("/api/email/google/action", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: selectedThread.id, action: actionName }) }); const data = await readJson(response); if (!response.ok) setStatus(String(data.error || "Gmail action failed")); else { setSelectedThread(null); await loadThreads(); } }
  useEffect(() => { void statusCheck(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, []);
  useEffect(() => { if (gmail.connected) void loadThreads(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [gmail.connected]);
  const filtered = threads.filter((thread) => !filter || `${thread.latest?.from} ${thread.latest?.subject} ${thread.latest?.snippet}`.toLowerCase().includes(filter.toLowerCase()));
  return <div className="inbox-layout"><section className="panel stack inbox-list"><div className="spread"><div><h2>Gmail inbox</h2><p className="muted small">{gmail.connected ? `connected as ${gmail.email}` : gmail.configured ? "OAuth configured; connect your mailbox" : "add Google OAuth credentials first"}</p></div>{gmail.connected ? <button onClick={() => void fetch("/api/email/google/disconnect", { method: "POST" }).then(() => { setGmail({ ...gmail, connected: false, email: "" }); setThreads([]); })}>disconnect</button> : <a className="buttonlike" href="/api/email/google/start?returnTo=%2Fbusiness%3Fsection%3Dinbox">connect Gmail</a>}</div><div className="field-with-button"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="in:inbox is:unread or from:..." /><button onClick={() => void loadThreads()} disabled={!gmail.connected || mailLoading}>search</button></div><div className="thread-list">{filtered.map((thread) => <button className={`thread-row ${thread.unread ? "unread" : ""} ${selectedThread?.id === thread.id ? "active" : ""}`} key={thread.id} onClick={() => void openThread(thread)}><div className="spread"><strong>{thread.latest?.from || "unknown"}</strong><span className="muted small">{dateLabel(thread.latest?.date || "")}</span></div><p>{thread.latest?.subject || "(no subject)"}</p><span className="muted small">{thread.latest?.snippet} · {thread.messageCount} message{thread.messageCount === 1 ? "" : "s"}</span></button>)}</div></section>
    <section className="panel stack inbox-thread"><div className="spread"><h2>{selectedThread ? selectedThread.messages.at(-1)?.subject : "Read and reply"}</h2>{selectedThread && <div className="row"><button onClick={() => void gmailAction("unread")}>mark unread</button><button onClick={() => void gmailAction("archive")}>archive</button></div>}</div>{selectedThread ? <div className="mail-conversation">{selectedThread.messages.map((message) => <article className="mail-message" key={message.id}><div className="spread"><strong>{message.from}</strong><span className="muted small">{dateLabel(message.date)}</span></div><p className="muted small">to {message.to}</p><pre className="mail-body">{message.body}</pre>{message.attachments.length > 0 && <div className="row">{message.attachments.map((attachment) => <a className="buttonlike" key={attachment.attachmentId} href={`/api/email/google/attachment?messageId=${encodeURIComponent(message.id)}&attachmentId=${encodeURIComponent(attachment.attachmentId)}&filename=${encodeURIComponent(attachment.filename)}&type=${encodeURIComponent(attachment.mimeType)}`}>{attachment.filename} ({Math.ceil(attachment.size / 1024)} KB)</a>)}</div>}</article>)}</div> : <p className="muted">Choose a thread, or compose a new message below.</p>}<hr/><label className="stack small">Link to company<LeadPicker leads={leads} value={selectedLeadId} onChange={setSelectedLeadId} /></label><label className="stack small">To<input value={to} onChange={(event) => setTo(event.target.value)} placeholder="business@example.com" /></label><label className="stack small">Subject<input value={subject} onChange={(event) => setSubject(event.target.value)} /></label><label className="stack small">Message<textarea className="mail-compose" value={body} onChange={(event) => setBody(event.target.value)} /></label><div className="row"><button onClick={() => void send()} disabled={!gmail.connected || mailLoading || !to || !subject || !body}>send through Gmail</button><button onClick={() => { setSelectedThread(null); setTo(""); setSubject(""); setBody(""); }}>new message</button></div></section>
  </div>;
}

function SmsView(props: Shared) {
  const { leads, workspace, selectedLeadId, setSelectedLeadId, selectedLead, leadMap, filter, setStatus, loadAll } = props;
  const [configured, setConfigured] = useState(false); const [to, setTo] = useState(""); const [body, setBody] = useState(""); const [sending, setSending] = useState(false);
  async function sync() { const response = await fetch("/api/sms/messages", { cache: "no-store" }); const data = await readJson(response); if (response.ok) setConfigured(Boolean(data.configured)); else setStatus(String(data.error || "SMS load failed")); }
  useEffect(() => { void sync(); }, []);
  useEffect(() => { if (selectedLead?.phone) setTo(cleanPhone(selectedLead.phone)); }, [selectedLead?.phone]);
  async function send() { setSending(true); try { const response = await fetch("/api/sms/messages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId: selectedLeadId, to, body }) }); const data = await readJson(response); if (!response.ok) throw new Error(String(data.error || "SMS failed")); setBody(""); setStatus(`SMS ${data.status || "queued"}`); await loadAll(); } catch (error) { setStatus(errorText(error)); } finally { setSending(false); } }
  const messages = workspace.messages.filter((message) => message.channel === "sms" && (!selectedLeadId || message.leadId === selectedLeadId) && (!filter || `${message.sender} ${message.recipient} ${message.body}`.toLowerCase().includes(filter.toLowerCase())));
  return <div className="ops-two-column"><section className="panel stack"><div className="spread"><h2>Text messages</h2><span className={configured ? "badge" : "badge warn"}>{configured ? "TWILIO READY" : "NOT CONFIGURED"}</span></div><p className="muted small">Use this for warm leads, requested follow-ups, and customers. Incoming replies and delivery states appear in the conversation history.</p><label className="stack small">Company<LeadPicker leads={leads} value={selectedLeadId} onChange={setSelectedLeadId} /></label><label className="stack small">International number<input value={to} onChange={(event) => setTo(event.target.value)} placeholder="+358401234567" /></label><label className="stack small">Message<textarea value={body} maxLength={1600} onChange={(event) => setBody(event.target.value)} /></label><div className="spread"><span className="muted small">{body.length} characters · approximately {Math.max(1, Math.ceil(body.length / 153))} SMS segment(s)</span><button onClick={() => void send()} disabled={!configured || sending || !to || !body.trim()}>send SMS</button></div><div className="scan-card"><strong>Twilio webhooks</strong><p className="muted small">Incoming: <code>/api/sms/incoming</code><br/>Status callbacks are attached automatically. Set APP_BASE_URL to your production Vercel URL.</p></div></section><section className="panel stack"><div className="spread"><h2>SMS conversation</h2><span className="badge">{messages.length}</span></div>{messages.map((message) => <div className={`sms-bubble ${message.direction}`} key={message.id}><div className="spread"><strong>{message.direction === "inbound" ? message.sender : leadMap.get(message.leadId)?.name || message.recipient}</strong><span className="muted small">{dateLabel(message.createdAt)}</span></div><p>{message.body}</p><span className="muted small">{message.status || message.direction}</span></div>)}{!messages.length && <p className="muted">No SMS messages for this company.</p>}</section></div>;
}

function AuditsView(props: Shared) {
  const { leads, workspace, selectedLeadId, setSelectedLeadId, selectedLead, setStatus, loadAll } = props;
  const [strategy, setStrategy] = useState("mobile"); const [url, setUrl] = useState(""); const [running, setRunning] = useState(false); const [liveAudit, setLiveAudit] = useState<Audit | null>(null);
  useEffect(() => { if (selectedLead?.website) setUrl(selectedLead.website); }, [selectedLead?.website]);
  async function run() { if (!url) return; setRunning(true); setStatus("running full website audit and PageSpeed checks..."); try { const response = await fetch("/api/business/audit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId: selectedLeadId, url, strategy }) }); const data = await readJson(response); if (!response.ok) throw new Error(String(data.error || "audit failed")); setLiveAudit(data.audit as Audit); setStatus("audit complete"); await loadAll(); } catch (error) { setStatus(errorText(error)); } finally { setRunning(false); } }
  const audits = workspace.audits.filter((item) => !selectedLeadId || item.leadId === selectedLeadId); const current = liveAudit || audits[0] || null;
  function report() { if (!current) return; const lead = leads.find((item) => item.id === current.leadId); const html = `<!doctype html><meta charset="utf-8"><title>Website audit</title><style>body{font:16px Arial;max-width:900px;margin:40px auto;line-height:1.5}h1{border-bottom:2px solid #111}.high{color:#a00}.medium{color:#a60}.low{color:#555}img{max-width:100%;border:1px solid #aaa}</style><h1>Website audit: ${lead?.name || current.url}</h1><p>${current.url}</p><h2>Scores</h2><p>Overall ${current.score}/100 · Performance ${current.performance ?? "?"} · Accessibility ${current.accessibility ?? "?"} · SEO ${current.seo ?? "?"} · Best practices ${current.bestPractices ?? "?"}</p>${current.screenshot ? `<img src="${current.screenshot}">` : ""}<h2>Issues</h2><ol>${current.issues.map((issue) => `<li class="${issue.severity}"><strong>${issue.label}</strong>${issue.detail ? `<br>${issue.detail}` : ""}</li>`).join("")}</ol><h2>Facts</h2><pre>${JSON.stringify(current.facts, null, 2)}</pre>`; download(`${(lead?.name || "website").replace(/[^a-z0-9]+/gi,"-")}-audit.html`, html, "text/html;charset=utf-8"); }
  return <div className="ops-two-column"><section className="panel stack"><h2>Professional website audit</h2><label className="stack small">Company<LeadPicker leads={leads} value={selectedLeadId} onChange={setSelectedLeadId} /></label><label className="stack small">Website<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://company.fi" /></label><label className="stack small">Device<select value={strategy} onChange={(event) => setStrategy(event.target.value)}><option value="mobile">mobile</option><option value="desktop">desktop</option></select></label><button onClick={() => void run()} disabled={running || !url}>{running ? "auditing..." : "run full audit"}</button><p className="muted small">Checks metadata, mobile setup, contact actions, privacy links, structured data, broken internal links, and PageSpeed/Lighthouse scores. Browserless can add a screenshot and render difficult sites.</p><h3>History</h3>{audits.map((audit) => <button className="lead-row" key={audit.id} onClick={() => setLiveAudit(audit)}><span><strong>{audit.url}</strong><span className="muted small">{dateLabel(audit.createdAt)} · {audit.strategy}</span></span><span className="badge">{audit.score}</span></button>)}</section><section className="panel stack"><div className="spread"><h2>Audit result</h2><button onClick={report} disabled={!current}>download report</button></div>{!current ? <p className="muted">Run an audit or choose a saved result.</p> : <><div className="metric-grid"><Metric label="overall" value={`${current.score}/100`} /><Metric label="performance" value={current.performance ?? "?"} /><Metric label="accessibility" value={current.accessibility ?? "?"} /><Metric label="SEO" value={current.seo ?? "?"} /><Metric label="best practices" value={current.bestPractices ?? "?"} /></div>{current.screenshot && <img className="audit-shot" src={current.screenshot} alt="Website screenshot from audit" />}<div className="issue-list">{current.issues.map((issue, index) => <div className={`issue ${issue.severity}`} key={`${issue.label}-${index}`}><span className="badge">{issue.severity}</span><div><strong>{issue.label}</strong>{issue.detail && <p className="muted small">{issue.detail}</p>}</div></div>)}</div></>}</section></div>;
}

function ProposalsView(props: Shared) {
  const { leads, workspace, selectedLeadId, setSelectedLeadId, selectedLead, leadMap, setStatus, action, loadAll } = props;
  const [title, setTitle] = useState("Website redesign proposal"); const [setup, setSetup] = useState("750"); const [monthly, setMonthly] = useState("50"); const [deposit, setDeposit] = useState("250"); const [validUntil, setValidUntil] = useState(""); const [deliveryDays, setDeliveryDays] = useState("14"); const [revisions, setRevisions] = useState("2"); const [items, setItems] = useState("Custom responsive website:500\nContact form and lead storage:100\nSEO and Google setup:150\nMaintenance:50/month"); const [notes, setNotes] = useState("Includes the agreed pages, mobile layout, contact form, deployment, and two revision rounds.");
  const parseItems = () => items.split(/\n+/).map((line) => { const [label, raw = "0"] = line.split(":"); return { label: label.trim(), amount: amountFrom(raw), recurring: /month|monthly|\/kk/i.test(raw) }; }).filter((item) => item.label);
  async function save() { if (!selectedLeadId) return; try { await action("proposal.save", { leadId: selectedLeadId, title, status: "draft", currency: "EUR", setupAmount: amountFrom(setup), monthlyAmount: amountFrom(monthly), depositAmount: amountFrom(deposit), validUntil, deliveryDays: Number(deliveryDays), revisions: Number(revisions), lineItems: parseItems(), notes }); setStatus("proposal saved"); await loadAll(); } catch (error) { setStatus(errorText(error)); } }
  function proposalHtml(proposal?: Proposal) { const p = proposal || { title, setupAmount: amountFrom(setup), monthlyAmount: amountFrom(monthly), depositAmount: amountFrom(deposit), validUntil, deliveryDays: Number(deliveryDays), revisions: Number(revisions), lineItems: parseItems(), notes, currency: "EUR" } as Proposal; const company = selectedLead || leadMap.get(p.leadId); return `<!doctype html><meta charset="utf-8"><title>${p.title}</title><style>body{font:16px Arial;max-width:850px;margin:50px auto;line-height:1.55;color:#151515}header{border-bottom:3px solid #111}table{width:100%;border-collapse:collapse}td,th{padding:12px;border-bottom:1px solid #ddd;text-align:left}.total{font-size:22px;font-weight:bold}.terms{background:#f3f3f3;padding:20px}</style><header><h1>${p.title}</h1><p>Prepared by Jonas for ${company?.name || "Client"}</p></header><h2>Scope</h2><table>${p.lineItems.map((item) => `<tr><td>${item.label}</td><td>${money(item.amount, p.currency)}${item.recurring ? "/month" : ""}</td></tr>`).join("")}</table><p class="total">Setup: ${money(p.setupAmount,p.currency)} · Monthly: ${money(p.monthlyAmount,p.currency)}</p><div class="terms"><p>Deposit: ${money(p.depositAmount,p.currency)}</p><p>Delivery target: ${p.deliveryDays} days after materials and deposit.</p><p>Included revisions: ${p.revisions}</p><p>Valid until: ${p.validUntil || "14 days from issue"}</p></div><h2>Notes</h2><p>${p.notes}</p><h2>Acceptance</h2><p>Name: ________________________ Date: __________ Signature: ________________________</p>`; }
  const proposals = workspace.proposals.filter((item) => !selectedLeadId || item.leadId === selectedLeadId);
  return <div className="ops-two-column"><section className="panel stack"><h2>Proposal builder</h2><label className="stack small">Company<LeadPicker leads={leads} value={selectedLeadId} onChange={setSelectedLeadId} /></label><label className="stack small">Proposal title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><div className="grid tight-grid"><label className="stack small">Setup €<input value={setup} onChange={(event) => setSetup(event.target.value)} /></label><label className="stack small">Monthly €<input value={monthly} onChange={(event) => setMonthly(event.target.value)} /></label><label className="stack small">Deposit €<input value={deposit} onChange={(event) => setDeposit(event.target.value)} /></label><label className="stack small">Valid until<input type="date" value={validUntil} onChange={(event) => setValidUntil(event.target.value)} /></label><label className="stack small">Delivery days<input type="number" value={deliveryDays} onChange={(event) => setDeliveryDays(event.target.value)} /></label><label className="stack small">Revisions<input type="number" value={revisions} onChange={(event) => setRevisions(event.target.value)} /></label></div><label className="stack small">Line items, one per line: label:amount<textarea value={items} onChange={(event) => setItems(event.target.value)} /></label><label className="stack small">Terms and notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><div className="row"><button onClick={() => void save()} disabled={!selectedLeadId}>save proposal</button><button onClick={() => download("proposal.html", proposalHtml(), "text/html;charset=utf-8")} disabled={!selectedLead}>download preview</button></div></section><section className="panel stack"><h2>Saved proposals</h2>{proposals.map((proposal) => <div className="contact-row" key={proposal.id}><div><strong>{proposal.title}</strong><p>{leadMap.get(proposal.leadId)?.name || proposal.leadId}</p><span className="muted small">{money(proposal.setupAmount, proposal.currency)} setup · {money(proposal.monthlyAmount, proposal.currency)}/month · {proposal.status}</span></div><div className="row"><button onClick={() => download(`proposal-${proposal.id}.html`, proposalHtml(proposal), "text/html;charset=utf-8")}>download</button><button onClick={() => void action("transaction.add", { leadId: proposal.leadId, kind: "invoice", status: "unpaid", amount: proposal.depositAmount || proposal.setupAmount, currency: proposal.currency, dueAt: proposal.validUntil, description: `Deposit for ${proposal.title}` }).then(loadAll)}>create invoice</button></div></div>)}</section></div>;
}

function InquiriesView(props: Shared) {
  const { workspace, leadMap, filter, setStatus, action, loadAll, setSelectedLeadId } = props;
  const inquiries = workspace.inquiries.filter((item) => !filter || `${item.name} ${item.email} ${item.phone} ${item.message} ${leadMap.get(item.leadId)?.name}`.toLowerCase().includes(filter.toLowerCase()));
  async function change(item: Inquiry, status: string) { try { await action("inquiry.status", { id: item.id, status }); await loadAll(); } catch (error) { setStatus(errorText(error)); } }
  return <section className="panel stack"><div className="spread"><div><h2>Customer website inquiries</h2><p className="muted small">Generated client sites can send every form submission here as well as by email, so a failed email does not lose the lead.</p></div><span className="badge">{inquiries.filter((item) => item.status === "new").length} NEW</span></div><div className="inquiry-grid">{inquiries.map((item) => <article className={`inquiry-card ${item.status === "new" ? "unread" : ""}`} key={item.id}><div className="spread"><div><span className="badge">{item.status}</span><h3>{item.name || "Unnamed inquiry"}</h3></div><span className="muted small">{dateLabel(item.createdAt)}</span></div><p className="muted small">for {leadMap.get(item.leadId)?.name || item.leadId || "unassigned site"} · {item.sourceSite}</p><p>{item.message}</p><div className="row">{item.email && <a className="buttonlike" href={`mailto:${item.email}`}>{item.email}</a>}{item.phone && <a className="buttonlike" href={`tel:${cleanPhone(item.phone)}`}>{item.phone}</a>}<button onClick={() => { setSelectedLeadId(item.leadId); void change(item, "contacted"); }}>mark contacted</button><button onClick={() => void change(item, "closed")}>close</button></div></article>)}</div>{!inquiries.length && <p className="muted">No customer site inquiries yet.</p>}</section>;
}

function MoneyView(props: Shared) {
  const { leads, workspace, selectedLeadId, setSelectedLeadId, leadMap, setStatus, action, loadAll } = props;
  const [kind, setKind] = useState("invoice"); const [txStatus, setTxStatus] = useState("unpaid"); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [dueAt, setDueAt] = useState("");
  const paid = workspace.transactions.filter((item) => item.status === "paid").reduce((sum, item) => sum + item.amount, 0);
  const unpaid = workspace.transactions.filter((item) => item.status === "unpaid").reduce((sum, item) => sum + item.amount, 0);
  const expenses = workspace.transactions.filter((item) => item.kind === "expense").reduce((sum, item) => sum + item.amount, 0);
  const mrr = workspace.proposals.filter((item) => ["accepted","won","active"].includes(item.status)).reduce((sum, item) => sum + item.monthlyAmount, 0);
  const won = leads.filter((lead) => lead.status === "won").length; const contacted = leads.filter((lead) => ["contacted","followup","interested","won"].includes(lead.status)).length;
  async function add() { if (!amount) return; try { await action("transaction.add", { leadId: selectedLeadId, kind, status: txStatus, amount: amountFrom(amount), currency: "EUR", dueAt, paidAt: txStatus === "paid" ? new Date().toISOString() : "", description }); setAmount(""); setDescription(""); await loadAll(); } catch (error) { setStatus(errorText(error)); } }
  const transactions = workspace.transactions;
  return <><section className="metric-grid money-metrics"><Metric label="paid revenue" value={money(paid)} /><Metric label="unpaid invoices" value={money(unpaid)} /><Metric label="recorded expenses" value={money(expenses)} /><Metric label="profit after recorded expenses" value={money(paid - expenses)} /><Metric label="monthly recurring" value={money(mrr)} /><Metric label="contact → win" value={contacted ? `${Math.round((won/contacted)*100)}%` : "0%"} /></section><div className="ops-two-column"><section className="panel stack"><h2>Add money record</h2><label className="stack small">Company<LeadPicker leads={leads} value={selectedLeadId} onChange={setSelectedLeadId} /></label><div className="grid tight-grid"><label className="stack small">Type<select value={kind} onChange={(event) => setKind(event.target.value)}>{["invoice","payment","deposit","subscription","expense","refund"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="stack small">Status<select value={txStatus} onChange={(event) => setTxStatus(event.target.value)}>{["unpaid","paid","overdue","cancelled","refunded"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="stack small">Amount €<input value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className="stack small">Due date<input type="date" value={dueAt} onChange={(event) => setDueAt(event.target.value)} /></label></div><label className="stack small">Description<input value={description} onChange={(event) => setDescription(event.target.value)} /></label><button onClick={() => void add()} disabled={!amount}>save record</button></section><section className="panel stack"><div className="spread"><h2>Ledger</h2><button onClick={() => download("business-ledger.csv", ["date,company,type,status,amount,currency,description", ...transactions.map((item) => [item.createdAt, leadMap.get(item.leadId)?.name || item.leadId, item.kind, item.status, item.amount, item.currency, item.description].map(csvCell).join(","))].join("\n"), "text/csv;charset=utf-8")}>export CSV</button></div>{transactions.map((item) => <div className="contact-row" key={item.id}><div><strong>{item.kind}: {item.description || "record"}</strong><p className="muted small">{leadMap.get(item.leadId)?.name || "general"} · {dateLabel(item.createdAt)} · due {item.dueAt || "—"}</p></div><div><strong>{money(item.amount,item.currency)}</strong><br/><span className={item.status === "paid" ? "badge" : "badge warn"}>{item.status}</span></div></div>)}</section></div></>;
}

function SetupView(props: Shared) {
  const { workspace } = props;
  const base = typeof window === "undefined" ? "https://your-dashboard.vercel.app" : window.location.origin;
  return <div className="ops-two-column"><section className="panel stack"><h2>Required Vercel variables</h2><pre>{`DATABASE_URL=...\nAUTH_SECRET=...\nAPP_BASE_URL=${base}\n\n# Gmail inbox + sending\nGOOGLE_OAUTH_CLIENT_ID=...\nGOOGLE_OAUTH_CLIENT_SECRET=...\nGOOGLE_OAUTH_REDIRECT_URI=${base}/api/email/google/callback\n\n# SMS\nTWILIO_ACCOUNT_SID=...\nTWILIO_AUTH_TOKEN=...\nTWILIO_FROM_NUMBER=+...\n# or TWILIO_MESSAGING_SERVICE_SID=...\n\n# Deeper scanning and screenshots (optional)\nBROWSERLESS_TOKEN=...\nBROWSERLESS_BASE_URL=https://production-sfo.browserless.io\n\n# Faster PageSpeed quota (optional)\nPAGESPEED_API_KEY=...\n\n# Generated customer sites\nINQUIRY_WEBHOOK_SECRET=use-a-long-random-secret`}</pre><h3>Webhook URLs</h3><pre>{`Twilio incoming SMS: ${base}/api/sms/incoming\nGenerated-site inquiries: ${base}/api/business/inquiries/public`}</pre></section><section className="panel stack"><h2>Search and system history</h2>{workspace.searchRuns.map((run) => <div className="contact-row" key={run.id}><div><strong>{run.query} · {run.location}</strong><p className="muted small">{dateLabel(run.createdAt)} · {run.status} · grid {String(run.bounds.grid || 1)} · radius {String(run.bounds.radius || "?")}</p></div><div><span className="badge">{run.foundCount} found</span><p className="muted small">{run.apiRequests} API calls</p></div></div>)}<div className="scan-card"><strong>Architecture</strong><p className="muted small">Neon stores CRM records, Gmail tokens encrypted with AUTH_SECRET, messages, audits, proposals, payments, and inquiries. Vercel runs the APIs. Gmail and Twilio remain optional and fail with a clear setup message when disabled.</p></div></section></div>;
}
